
CREATE TABLE DEPOSIT(
 ACTNO VARCHAR(5),
 CNAME VARCHAR(18),
 BNAME VARCHAR(18),
 AMOUNT NUMERIC(8,2),
 ADATE DATE,
);

CREATE TABLE BRANCH(
 BNAME VARCHAR(25),
 CITY VARCHAR(18),
);

CREATE TABLE CUSTOMER(
 CNAME VARCHAR(25),
 CITY VARCHAR(18),
);

CREATE TABLE BORROW(
 LOANNO VARCHAR(5),
 CNAME VARCHAR(18),
 BNAME VARCHAR(18),
 AMOUNT NUMERIC(8,2),
);

INSERT INTO DEPOSIT
VALUES('105','SOMO','Andheri',2000,'1996-03-31');
INSERT INTO DEPOSIT
VALUES('106','Sandip','Andheri',2000,'1996-03-31');
INSERT INTO DEPOSIT
VALUES('107','Shivani','Vihar',1000,'1995-09-05');
INSERT INTO DEPOSIT
VALUES('108','Kranti','Nehru place',5000,'1995-07-02');
INSERT INTO DEPOSIT
VALUES('109','Naren','powai',7000,'1995-08-10');

INSERT INTO BRANCH
VALUES('Dharampeth','Nagpur');
INSERT INTO BRANCH
VALUES('M.G.Road','Bangalore');
INSERT INTO BRANCH
VALUES('Nehru place','Delhi');
INSERT INTO BRANCH
VALUES('powai','Bombay');
INSERT INTO BRANCH
VALUES('Newtown','Kolkata');

INSERT INTO CUSTOMER
VALUES('Pramod','Nagpur');
INSERT INTO CUSTOMER
VALUES('sandip','Surat');
INSERT INTO CUSTOMER
VALUES('Shivani','Bombay');
INSERT INTO CUSTOMER
VALUES('Kranti','Bombay');
INSERT INTO CUSTOMER
VALUES('Naren','Bombay');

INSERT INTO BORROW
VALUES('375','Pramod','Virar','8000');
INSERT INTO BORROW
VALUES('481','Kranti','Nehru place','3000');
INSERT INTO BORROW
VALUES('482','SOMO','Newtown','3000');

SELECT SUM(AMOUNT)
FROM BORROW;
--WHERE NOT LOANNO IS NULL;


SELECT SUM(AMOUNT)
FROM DEPOSIT;


SELECT SUM(AMOUNT)
FROM BRANCH JOIN BORROW
ON BORROW.BNAME=BRANCH.BNAME
WHERE BRANCH.BNAME='Nehru Place';
--changed to nehru place from Andheri

SELECT SUM(AMOUNT)
FROM DEPOSIT
WHERE ADATE>'1996-01-01';

SELECT SUM(AMOUNT)
FROM CUSTOMER JOIN DEPOSIT
ON CUSTOMER.CNAME=DEPOSIT.CNAME
WHERE CITY = 'Surat'; --changed to surat from nagpur

SELECT MAX(AMOUNT)
FROM DEPOSIT JOIN CUSTOMER
ON CUSTOMER.CNAME=DEPOSIT.CNAME
WHERE CITY = 'Bombay';
--changed to Bombay

SELECT COUNT(CITY)
FROM BRANCH;

SELECT COUNT(CITY)
FROM CUSTOMER;

SELECT BNAME, AMOUNT
FROM DEPOSIT;

SELECT CNAME, BNAME, AMOUNT
FROM DEPOSIT
WHERE ADATE>'1996-01-01';

SELECT COUNT(CNAME)
FROM CUSTOMER;

SELECT BNAME,COUNT(CNAME)
FROM DEPOSIT
GROUP BY BNAME;

SELECT MAX(AMOUNT)
FROM BORROW
WHERE BNAME='Newtown';

SELECT BNAME
FROM DEPOSIT
GROUP BY BNAME
HAVING SUM(AMOUNT)>4000;

--3o(oracle only)
SELECT
'dbms' string
LENGTH('dbms') length,
FROM DUAL;

SELECT CNAME
FROM CUSTOMER
WHERE CNAME = UPPER(CNAME) COLLATE SQL_LATIN1_GENERAL_CP1_CS_AS;
--for case sensitive selection

SELECT SUBSTRING(CNAME,5,7) AS SUBSTRING
FROM DEPOSIT
WHERE CNAME = 'shivani';

UPDATE DEPOSIT SET ACTNO = CONCAT('00',ACTNO);

SELECT * FROM DEPOSIT
ORDER BY ACTNO;

UPDATE DEPOSIT SET ADATE = ADD_MONTHS(ADATE,3);

SELECT ROUND(15.6789,2), TRUNCATE(15.6789,2) FROM DUAL; 
